### ISSUE TITLE
Comment alignment in lines with if instructions

### ISSUE THREAD

**Issue by reeelix** [LMH01/alpha_tui#82] opened 2024-06-27 13:12 UTC
Comments are indented by one space to much in lines with if instructions
![grafik](https://github.com/LMH01/alpha_tui/assets/127255628/db989eeb-7737-4f23-b978-d7f2eaa7d180)

**Comment by LMH01** [comment] 2024-06-27 19:00
Interesting find, I will see if and when I can fix that.

**Comment by LMH01** [comment] 2024-10-18 20:23
I am unable to reproduce the issue. Could you please try to find and sent me the source code that resulted in this bug so I can try to reproduce it?

**Comment by LMH01** [comment] 2024-10-18 20:25
Nevermind, I am able to reproduce something similar using the program in #84.

**Comment by LMH01** [comment] 2024-10-19 08:56
Problem is fixed and fix will be included in next release.

**Closed by LMH01** 2024-10-19 08:56 UTC
Labels: bug, accepted
